
Vagrant.configure("2") do |config|
  config.vm.box = "vm-lab-automation/p4-tutorial"
  config.ssh.username = "p4"
  config.ssh.password = "p4"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "P4-tip"
    vb.memory = 2048
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    vb.customize ["storageattach", :id, 
                "--storagectl", "IDE Controller", 
                "--port", "0", "--device", "0", 
                "--type", "dvddrive", 
                "--medium", "emptydrive"]    
    vb.customize ["modifyvm", :id, "--vram", "32"]
  end
  
  config.vm.network "forwarded_port", guest: 3389, host: 6001, auto_correct: true
end
