# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "p4-tutorial" do |tutorial|
  config.ssh.username = "p4"
  config.ssh.password = "p4"
  end
  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.has_ssh = true
  end
  #config.vm.synced_folder '.', '/vagrant', disabled: true  
  config.vm.hostname = "p4"
  config.vm.provision "file", source: "p4-logo.png",   destination: "/home/p4/p4-logo.png"
  config.vm.provision "file", source: "p4_16-mode.el", destination: "/home/p4/p4_16-mode.el"
  config.vm.provision "file", source: "p4.vim",        destination: "/home/p4/p4.vim"
  config.vm.provision "shell", path: "root-bootstrap.sh"
  #config.vm.provision "shell", privileged: false, path: "user-bootstrap.sh"
end
